-- ============================================================
-- ORLENE SEED DATA
-- Run last, after all schema, views, procedures, triggers
-- ============================================================
USE orlene_db;

-- Disable trigger temporarily for clean seeding
SET FOREIGN_KEY_CHECKS = 0;

-- ------------------------------------------------------------
-- USERS
-- admin@orlene.com / admin123
-- user@orlene.com  / user123
-- user2@orlene.com / user123
-- ------------------------------------------------------------
INSERT INTO users (name, email, password_hash, phone, nid, role) VALUES
('Orlene Admin',    'admin@orlene.com',  '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '01700000000', 'ADMIN001', 'admin'),
('Rahim Hossain',   'user@orlene.com',   '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '01811111111', 'NID123456', 'user'),
('Fatema Begum',    'user2@orlene.com',  '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '01722222222', 'NID789012', 'user'),
('Karim Uddin',     'user3@orlene.com',  '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '01933333333', 'NID345678', 'user');

-- Note: password hash above is the Laravel/common test hash for 'password'
-- Replace with actual hashes generated by PHP:
-- password_hash('admin123', PASSWORD_DEFAULT) for admin
-- password_hash('user123', PASSWORD_DEFAULT) for users

-- ------------------------------------------------------------
-- CATEGORIES
-- ------------------------------------------------------------
INSERT INTO categories (name, description) VALUES
('PHONE', 'Flagship smartphones and phone accessories for daily rentals'),
('GEAR',  'Adventure and outdoor equipment for hiking, camping, and cycling');

-- ------------------------------------------------------------
-- SUBCATEGORIES
-- ------------------------------------------------------------
INSERT INTO subcategories (category_id, name) VALUES
(1, 'Flagship Smartphones'),
(1, 'Phone Accessories'),
(2, 'Hiking'),
(2, 'Camping'),
(2, 'Cycling'),
(2, 'Water Sports'),
(2, 'Other Gear');

-- ------------------------------------------------------------
-- PRODUCTS
-- subcategory_id: 1=Flagship Phones, 2=Phone Accessories,
--                3=Hiking, 4=Camping, 5=Cycling, 6=Water, 7=Other
-- ------------------------------------------------------------
INSERT INTO products (subcategory_id, name, description, daily_rate, stock_qty, status, rental_count, maintenance_threshold, image_path) VALUES
-- Flagship Phones
(1, 'Samsung Galaxy S25 Ultra',
 'Latest Samsung flagship with 200MP camera, S Pen, 12GB RAM. Includes original charger and protective case.',
 500.00, 3, 'AVAILABLE', 0, 5, 'assets/img/products/samsung_s25.jpg'),

(1, 'Google Pixel 9 Pro',
 'Google Pixel 9 Pro with AI photography features, 7 years of updates, 50MP main camera.',
 450.00, 2, 'AVAILABLE', 0, 5, 'assets/img/products/pixel9.jpg'),

(1, 'iPhone 16 Pro Max',
 'Apple iPhone 16 Pro Max with A18 Pro chip, 48MP camera system, titanium design.',
 550.00, 2, 'AVAILABLE', 0, 5, 'assets/img/products/iphone16.jpg'),

-- Phone Accessories
(2, 'Anker 26800mAh Power Bank',
 'High-capacity 26800mAh power bank. Charges 2 phones simultaneously. USB-C + USB-A ports.',
 80.00, 5, 'AVAILABLE', 0, 10, 'assets/img/products/powerbank.jpg'),

(2, 'Universal Phone Tripod Kit',
 'Flexible tripod with Bluetooth remote. Works with all phones. Great for solo travel photography.',
 60.00, 4, 'AVAILABLE', 0, 10, 'assets/img/products/tripod.jpg'),

(2, 'Wide Angle Lens Kit',
 'Clip-on 0.45x wide-angle lens + 15x macro. Compatible with all smartphones.',
 50.00, 6, 'AVAILABLE', 0, 10, 'assets/img/products/lens_kit.jpg'),

-- Hiking
(3, '2-Person Hiking Tent',
 'Lightweight 2-person dome tent. Water-resistant. Easy 10-minute setup. Includes stakes and rainfly.',
 200.00, 3, 'AVAILABLE', 0, 5, 'assets/img/products/tent.jpg'),

(3, 'Trekking Poles (Pair)',
 'Aluminum anti-shock trekking poles. Adjustable 65–135cm. Comfortable cork grip.',
 80.00, 5, 'AVAILABLE', 0, 10, 'assets/img/products/poles.jpg'),

(3, 'Hiking Backpack 50L',
 'OSPREY 50L trekking backpack with rain cover. Multiple compartments. Hip belt for comfort.',
 150.00, 3, 'AVAILABLE', 0, 5, 'assets/img/products/backpack.jpg'),

-- Camping
(4, 'Sleeping Bag (0°C rated)',
 'Mummy-style sleeping bag rated to 0°C. Lightweight 1.2kg. Compression sack included.',
 120.00, 4, 'AVAILABLE', 0, 5, 'assets/img/products/sleeping_bag.jpg'),

(4, 'Camping Lantern + Stove Kit',
 'LED lantern (500 lumens) + portable gas stove combo. Perfect for overnight camping.',
 100.00, 4, 'AVAILABLE', 0, 5, 'assets/img/products/lantern_stove.jpg'),

(4, 'Camping Cookware Set',
 '6-piece aluminum cookware: pot, pan, bowls, spork. Compact nesting design.',
 70.00, 5, 'AVAILABLE', 0, 10, 'assets/img/products/cookware.jpg'),

-- Cycling
(5, 'Trek Mountain Bike (M)',
 'Trek Marlin 5 mountain bike, medium frame, 27.5" wheels, 21-speed Shimano gears.',
 350.00, 2, 'AVAILABLE', 0, 5, 'assets/img/products/mtb.jpg'),

(5, 'Cycling Helmet + Gloves',
 'Giro cycling helmet (adjustable) + padded cycling gloves set. Multiple sizes available.',
 60.00, 6, 'AVAILABLE', 0, 10, 'assets/img/products/helmet.jpg'),

-- Water Sports
(6, 'Kayak Paddle (Fiberglass)',
 'Lightweight fiberglass kayak paddle, 220cm, adjustable feather angle. For flatwater kayaking.',
 130.00, 4, 'AVAILABLE', 0, 5, 'assets/img/products/kayak_paddle.jpg'),

-- Other
(7, 'Binoculars 10x42',
 'High-quality 10x42 waterproof binoculars for birdwatching, hiking and camping. Wide field of view.',
 90.00, 3, 'AVAILABLE', 0, 10, 'assets/img/products/binoculars.jpg');

-- ------------------------------------------------------------
-- SAMPLE RENTALS (for demo purposes)
-- user_id=2 (Rahim), user_id=3 (Fatema)
-- product_id=1 (Samsung S25), product_id=7 (Tent), etc.
-- ------------------------------------------------------------

-- Rental 1: Completed rental (Samsung phone, Rahim)
INSERT INTO rentals (user_id, product_id, start_date, end_date, days, total_fee, status,
  use_area, use_city, use_landmark, use_lat, use_lng, pickup_at, returned_at)
VALUES (2, 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(CURDATE(), INTERVAL 7 DAY),
  3, 1500.00, 'COMPLETED',
  'Gulshan 1', 'Dhaka', 'Near Gulshan Circle 1',
  23.7925, 90.4078,
  DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY));

-- Inspection for rental 1
INSERT INTO inspections (rental_id, product_id, admin_id, result, notes, inspected_at)
VALUES (1, 1, 1, 'PASS', 'Product returned in good condition, screen clean, no damage.',
  DATE_SUB(NOW(), INTERVAL 6 DAY));

-- Rental 2: Active rental (Tent, Fatema, ends tomorrow)
INSERT INTO rentals (user_id, product_id, start_date, end_date, days, total_fee, status,
  use_area, use_city, use_landmark, use_lat, use_lng, pickup_at)
VALUES (3, 7, DATE_SUB(CURDATE(), INTERVAL 2 DAY), DATE_ADD(CURDATE(), INTERVAL 1 DAY),
  3, 600.00, 'ACTIVE',
  'Bandarban Sadar', 'Bandarban', 'Near Nilgiri Resort',
  22.1953, 92.2184,
  DATE_SUB(NOW(), INTERVAL 2 DAY));

-- Rental confirmation for rental 2 (pickup)
INSERT INTO rental_confirmations (rental_id, confirmed_by, confirm_type, confirmed_at)
VALUES (2, 3, 'PICKUP', DATE_SUB(NOW(), INTERVAL 2 DAY));

-- Rental 3: Pending approval (Pixel 9, Karim)
INSERT INTO rentals (user_id, product_id, start_date, end_date, days, total_fee, status,
  use_area, use_city, use_landmark, use_lat, use_lng)
VALUES (4, 2, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_ADD(CURDATE(), INTERVAL 4 DAY),
  3, 1350.00, 'PENDING',
  'Dhanmondi', 'Dhaka', 'Road 27, Dhanmondi',
  23.7461, 90.3742,
  NULL, NULL);

-- Rental 4: Returned (Mountain Bike, Rahim) — awaiting inspection
INSERT INTO rentals (user_id, product_id, start_date, end_date, days, total_fee, status,
  use_area, use_city, use_landmark, use_lat, use_lng, pickup_at, returned_at)
VALUES (2, 13, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY),
  2, 700.00, 'RETURNED',
  'Uttara Sector 11', 'Dhaka', 'Near Uttara Park',
  23.8759, 90.3795,
  DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY));

-- Update product 13 (Mountain Bike) to PENDING_INSPECTION
UPDATE products SET status = 'PENDING_INSPECTION' WHERE id = 13;

-- ------------------------------------------------------------
-- Set product 1 back to AVAILABLE (it was completed/returned)
-- ------------------------------------------------------------
UPDATE products SET status = 'AVAILABLE', rental_count = 1 WHERE id = 1;

-- Set product 7 (Tent) to RENTED (it's active)
UPDATE products SET status = 'RENTED' WHERE id = 7;

SET FOREIGN_KEY_CHECKS = 1;
